<%@ taglib prefix="props" tagdir="/WEB-INF/tags/props" %>
<%@ taglib prefix="l" tagdir="/WEB-INF/tags/layout" %>
<%@ taglib prefix="admin" tagdir="/WEB-INF/tags/admin" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="bs" tagdir="/WEB-INF/tags" %>

<jsp:useBean id="propertiesBean" scope="request" type="jetbrains.buildServer.controllers.BasePropertiesBean"/>
<jsp:useBean id="constants" class="net.portswigger.burp.api.teamcity.BurpScanConstantsBean"/>

<l:settingsGroup title="Burp scan">
  <tr>
    <th><label>URL of Burp API:</label></th>
    <td><props:textProperty name="${constants.apiUrl}" className="longField"/></td>
  </tr>

  <tr>
    <th><label>Scan definition in JSON format:</label></th>
    <td>
      <props:multilineProperty name="${constants.scanDefinition}"
                               className="longField"
                               linkTitle="Optional, in the format generated by the web service running on the Burp API endpoint"
                               cols="55" rows="5"
                               expanded="false" />
    </td>
  </tr>

  <tr>
    <th><label>Lowest severity issue required to fail the build:</label></th>
    <td>
      <props:selectProperty name="${constants.severityThreshold}">
        <c:forEach var="item" items="${constants.severities}">
          <props:option value="${item.name().toLowerCase()}"><c:out value="${item.display}"/></props:option>
        </c:forEach>
      </props:selectProperty>
    </td>
  </tr>

  <tr>
    <th><label>Lowest confidence issue required to fail the build:</label></th>
    <td>
      <props:selectProperty name="${constants.confidenceThreshold}">
        <c:forEach var="item" items="${constants.confidences}">
          <props:option value="${item.name().toLowerCase()}"><c:out value="${item.display}"/></props:option>
        </c:forEach>
      </props:selectProperty>
    </td>
  </tr>

  <tr>
    <th><label>Output issues in JSON form (verbose):</label></th>
    <td><props:checkboxProperty name="${constants.outputJsonIssues}"/></td>
  </tr>
</l:settingsGroup>

<i>Note that the dynamic input for this plugin is the content of the previous step's build output, specifically lines of the form "BURP_SCAN_URL = <URL to scan>"</i>